export type SchemaEncryption = "none" | "metadata_only" | "payload_reference" | "ciphertext";

export interface SchemaCatalogEntry {
  readonly table: string;
  readonly productPort: string;
  readonly lifecycle: string;
  readonly encryption: SchemaEncryption;
  readonly deletion: string;
  readonly migrationOwner: "@himawari-agent/persistence-sqlite";
}

function entry(
  table: string,
  productPort: string,
  lifecycle: string,
  encryption: SchemaEncryption,
  deletion: string,
): SchemaCatalogEntry {
  return Object.freeze({
    table,
    productPort,
    lifecycle,
    encryption,
    deletion,
    migrationOwner: "@himawari-agent/persistence-sqlite" as const,
  });
}

export const schemaCatalog: readonly SchemaCatalogEntry[] = Object.freeze([
  entry(
    "schema_migration_ledger",
    "PersistenceLifecyclePort",
    "immutable ledger",
    "none",
    "never delete while state root exists",
  ),
  entry(
    "schema_metadata",
    "PersistenceLifecyclePort",
    "current schema metadata",
    "none",
    "replace only through migration transaction",
  ),
  entry(
    "owners",
    "ProductStateRepositoryPort",
    "single active Owner",
    "metadata_only",
    "delete only through governed state-root teardown",
  ),
  entry(
    "owner_identity_bindings",
    "OwnerIdentityStatePort",
    "one-time bootstrap then break-glass repair",
    "metadata_only",
    "cascade only after Owner teardown",
  ),
  entry(
    "agents",
    "ProductStateRepositoryPort",
    "active to retired",
    "metadata_only",
    "cascade only after Owner teardown",
  ),
  entry(
    "deployments",
    "DeploymentAuthorityStatePort",
    "inactive_ready to active to retired",
    "metadata_only",
    "retain authority history",
  ),
  entry(
    "authority_leases",
    "AuthorityLeasePort",
    "active to released or expired",
    "metadata_only",
    "retain fence history",
  ),
  entry(
    "authority_transfers",
    "AuthorityTransferPort",
    "proposed to activated or abandoned",
    "metadata_only",
    "retain transfer tombstone",
  ),
  entry(
    "payloads",
    "PayloadStorePort",
    "active to trashed to deleted_verified",
    "ciphertext",
    "verify ciphertext removal before tombstone completion",
  ),
  entry(
    "threads",
    "ThreadMessageStorePort",
    "open to trashed to deleted_verified",
    "metadata_only",
    "governed cascade after active jobs resolve",
  ),
  entry(
    "thread_messages",
    "ThreadMessageStorePort",
    "committed and immutable",
    "payload_reference",
    "cascade with permanent Thread deletion",
  ),
  entry(
    "devices",
    "SessionDeviceStatePort",
    "active to revoked",
    "metadata_only",
    "cascade on Owner teardown",
  ),
  entry(
    "product_sessions",
    "SessionDeviceStatePort",
    "active to revoked",
    "metadata_only",
    "cascade on Owner teardown or explicit purge",
  ),
  entry(
    "triggers",
    "TriggerAdmissionPort",
    "admitted and immutable",
    "payload_reference",
    "cascade with governed task or Thread deletion",
  ),
  entry(
    "runs",
    "ProductStateRepositoryPort",
    "Run state machine",
    "metadata_only",
    "cascade with governed Thread or task deletion",
  ),
  entry(
    "turns",
    "TraceStorePort",
    "committed and immutable",
    "metadata_only",
    "cascade with Run deletion",
  ),
  entry(
    "run_checkpoints",
    "ProductStateRepositoryPort",
    "append-only revision",
    "payload_reference",
    "cascade with Run deletion",
  ),
  entry(
    "approval_requests",
    "AuthorizationStorePort",
    "pending to terminal",
    "payload_reference",
    "cascade with Run deletion",
  ),
  entry(
    "grants",
    "AuthorizationStorePort",
    "active to terminal",
    "metadata_only",
    "retain minimal authorization tombstone",
  ),
  entry(
    "authorization_usage",
    "AuthorizationStorePort",
    "append-only usage",
    "metadata_only",
    "cascade with Grant physical purge",
  ),
  entry(
    "capability_declarations",
    "CapabilityRegistryPort",
    "governed installation lifecycle",
    "payload_reference",
    "retain version/integrity tombstone",
  ),
  entry(
    "capability_handles",
    "CapabilityExecutionHandlePort",
    "active to terminal",
    "metadata_only",
    "cascade with declaration or Run purge",
  ),
  entry(
    "command_results",
    "ProductStateRepositoryPort",
    "immutable idempotent result",
    "metadata_only",
    "cascade with Agent teardown",
  ),
  entry(
    "product_state_records",
    "ProductStateRepositoryPort",
    "revision-checked current product state",
    "metadata_only",
    "cascade with Agent teardown after dependent workflows settle",
  ),
  entry(
    "reliable_events",
    "ReliableEventPort",
    "pending to published",
    "payload_reference",
    "retention purge after publication watermark",
  ),
  entry(
    "trace_events",
    "TraceStorePort",
    "append-only event",
    "payload_reference",
    "cascade with governed Run or Thread deletion",
  ),
  entry(
    "audit_records",
    "AuditLedgerPort",
    "append-only minimal audit",
    "payload_reference",
    "retain according to audit policy",
  ),
  entry(
    "deletion_tombstones",
    "SessionDeletionStatePort",
    "pending to verified",
    "metadata_only",
    "retain non-content deletion proof",
  ),
  entry(
    "scheduled_jobs",
    "BackgroundWorkStatePort",
    "active to paused or revoked",
    "payload_reference",
    "governed task deletion cascade",
  ),
  entry(
    "job_occurrences",
    "BackgroundWorkStatePort",
    "queued to terminal",
    "metadata_only",
    "cascade with governed task deletion",
  ),
  entry(
    "attention_decisions",
    "AttentionStatePort",
    "immutable decision",
    "payload_reference",
    "cascade with Run deletion",
  ),
  entry(
    "inbox_deliveries",
    "AttentionStatePort",
    "pending to delivered",
    "payload_reference",
    "cascade with governed Run or task deletion",
  ),
  entry(
    "thread_checkpoint_jobs",
    "ThreadCheckpointStatePort",
    "pending to terminal",
    "payload_reference",
    "cascade with Thread deletion",
  ),
  entry(
    "memory_generations",
    "ThreadCheckpointStatePort",
    "pending to terminal",
    "payload_reference",
    "cascade with checkpoint deletion",
  ),
  entry(
    "memory_records",
    "ProductMemoryStatePort",
    "active to archived or deleted_verified",
    "payload_reference",
    "product deactivation precedes projection cleanup",
  ),
  entry(
    "memory_provenance",
    "ProductMemoryStatePort",
    "source relationship",
    "metadata_only",
    "replace source with deleted marker when required",
  ),
  entry(
    "memory_projection_jobs",
    "MemoryProjectionPort",
    "pending to terminal",
    "metadata_only",
    "cascade after Memory deletion verification",
  ),
  entry(
    "memory_approval_requests",
    "SensitiveMemoryApprovalStatePort",
    "pending to committed or terminal rejection",
    "metadata_only",
    "cascade with source Run or generation deletion",
  ),
  entry(
    "github_installations",
    "GitHubIntegrationStatePort",
    "active to revoked",
    "metadata_only",
    "remove repository cache and retain minimal tombstone",
  ),
  entry(
    "github_repository_monitors",
    "GitHubIntegrationStatePort",
    "active to paused or revoked",
    "payload_reference",
    "cascade with installation purge",
  ),
  entry(
    "github_webhook_receipts",
    "GitHubIntegrationStatePort",
    "received to terminal",
    "payload_reference",
    "retention purge after occurrence normalization",
  ),
  entry(
    "github_coverage_gaps",
    "GitHubIntegrationStatePort",
    "open to closed",
    "metadata_only",
    "retain visible gap history",
  ),
  entry(
    "recovery_points",
    "RecoveryPointPort",
    "creating to terminal",
    "metadata_only",
    "purge by recovery retention watermark",
  ),
  entry(
    "backup_restore_markers",
    "RecoveryPointPort",
    "append-only operation marker",
    "metadata_only",
    "purge with recovery point",
  ),
  entry(
    "storage_health_samples",
    "HealthStatePort",
    "append-only bounded sample",
    "metadata_only",
    "purge by metrics retention",
  ),
  entry(
    "attention_policy_states",
    "AttentionStatePort",
    "revision-checked current policy state",
    "metadata_only",
    "cascade with Agent teardown",
  ),
  entry(
    "gateway_thread_snapshots",
    "GatewayReadModelPort",
    "replaceable bounded Thread projection",
    "payload_reference",
    "cascade with projected Thread deletion",
  ),
  entry(
    "gateway_run_snapshots",
    "GatewayReadModelPort",
    "replaceable bounded Run projection",
    "payload_reference",
    "cascade with projected Run deletion",
  ),
  entry(
    "gateway_stream_events",
    "GatewayReadModelPort",
    "cursor-ordered retained event projection",
    "payload_reference",
    "purge below retention watermark",
  ),
  entry(
    "reliable_event_consumptions",
    "ReliableEventConsumerDeduplicator",
    "append-only consumer receipt",
    "none",
    "cascade with Reliable Event retention",
  ),
  entry(
    "gateway_read_model_metadata",
    "GatewayReadModelPort",
    "projection and retention watermarks",
    "none",
    "replace only through projection transaction",
  ),
]);
