export type ContainerBackendErrorCode =
  | "CONTAINER_RUNTIME_UNAVAILABLE"
  | "CONTAINER_RUNTIME_CHANGED"
  | "CONTAINER_IMAGE_UNQUALIFIED"
  | "CONTAINER_RUNNER_UNQUALIFIED"
  | "CONTAINER_POLICY_UNSUPPORTED"
  | "CONTAINER_POLICY_MISMATCH"
  | "CONTAINER_IDENTITY_CONFLICT"
  | "CONTAINER_DEADLINE_PASSED"
  | "CONTAINER_EXECUTION_CLOSED"
  | "CONTAINER_NOT_RUNNING"
  | "CONTAINER_RESTARTED"
  | "CONTAINER_ARGUMENTS_INVALID"
  | "CONTAINER_COMMAND_TIMEOUT"
  | "CONTAINER_OUTPUT_UNKNOWN"
  | "CONTAINER_STOP_NOT_REQUESTED"
  | "CONTAINER_NOT_STOPPED"
  | "CONTAINER_STOP_UNVERIFIED"
  | "CONTAINER_DIRECTORY_UNRESOLVED"
  | "CONTAINER_DIRECTORY_CHANGED"
  | "CONTAINER_DIRECTORY_OWNER_UNSUPPORTED"
  | "CONTAINER_DIRECTORY_SCAN_LIMIT"
  | "CONTAINER_PROTECTED_FILE_UNMASKABLE"
  | "CONTAINER_GIT_METADATA_OUTSIDE"
  | "CONTAINER_DISK_GUARD_UNAVAILABLE"
  | "CONTAINER_DISK_FLOOR"
  | "CONTAINER_DISK_GUARD_TRIPPED"
  | "CONTAINER_EGRESS_UNAVAILABLE";

export class ContainerBackendError extends Error {
  readonly code: ContainerBackendErrorCode;

  constructor(code: ContainerBackendErrorCode, options?: { readonly cause?: unknown }) {
    super(code, options);
    this.name = "ContainerBackendError";
    this.code = code;
  }
}
