import messages from "./fixtures/v2/messages.json" with { type: "json" };

const authority = { deploymentId: "deployment-01", authorityEpoch: 8, fencingToken: 3 };
const scope = { ownerId: "owner-01", agentId: "agent-01" };
const actor = { actorType: "owner", actorId: "owner-01" } as const;

export function fixture(
  kind: "command" | "query" | "snapshot",
  type: string,
  payload: unknown,
): Record<string, unknown> {
  return {
    schemaVersion: "gateway.v2",
    kind,
    type,
    messageId: `fixture-${type}`,
    correlationId: `correlation-${type}`,
    causationId: null,
    dataClassification: "private",
    risk: kind === "command" ? "high" : "low",
    authorizationRef: kind === "command" ? "authorization-governance-01" : null,
    scope,
    authority,
    actor: kind === "snapshot" ? { actorType: "system", actorId: "agent-service-01" } : actor,
    ...(kind === "command" ? { idempotencyKey: `idempotency-${type}` } : {}),
    payload,
  };
}

export const governanceMessages = [
  fixture("query", "search.authorization.read", {}),
  fixture("command", "search.authorization.set", {
    expectedRevision: 0,
    enabled: true,
    recipient: "https://mcp.exa.ai",
  }),
  fixture("snapshot", "search.authorization.snapshot", {
    revision: 1,
    enabled: true,
    available: true,
    recipient: "https://mcp.exa.ai",
    generatedAt: "2026-09-11T00:00:00.000Z",
  }),
  fixture("command", "grant.revoke", {
    grantId: "grant-01",
    expectedRevision: 2,
    reasonCode: "owner-requested",
  }),
  fixture("command", "capability.review", {
    capabilityRef: "capability-01",
    expectedRevision: 2,
  }),
  fixture("command", "capability.install.approve", {
    capabilityRef: "capability-01",
    expectedRevision: 3,
    approvalRef: "approval-install-01",
  }),
  fixture("command", "capability.update.respond", {
    capabilityRef: "capability-01",
    expectedRevision: 5,
    decision: "approved",
    approvalRef: "approval-update-01",
  }),
  fixture("command", "capability.disable", {
    capabilityRef: "capability-01",
    expectedRevision: 7,
    reasonCode: "owner-disabled",
  }),
  fixture("command", "capability.rollback", {
    capabilityRef: "capability-01",
    expectedRevision: 8,
    reasonCode: "owner-rollback",
  }),
  fixture("query", "approval.detail", { approvalRequestId: "approval-01" }),
  fixture("query", "capability.list", {
    lifecycle: null,
    afterCursor: null,
    limit: 50,
  }),
  fixture("query", "capability.detail", { capabilityRef: "capability-01" }),
  fixture("query", "grant.list", { includeRevoked: true, afterCursor: null, limit: 50 }),
  fixture("query", "grant.detail", { grantId: "grant-01" }),
  fixture("snapshot", "approval.snapshot", {
    approvalRequestId: "approval-01",
    revision: 2,
    status: "pending",
    deliveryState: "deliverable",
    semanticSnapshotHash: "sha256:snapshot01",
    finalRisk: "high",
    recentAuthenticationRequired: true,
    recentAuthenticationRef: null,
    requestedAt: "2026-08-26T00:00:00.000Z",
    expiresAt: "2026-08-26T01:00:00.000Z",
    decidedAt: null,
    grantId: null,
    intent: {
      intentId: "intent-01",
      threadId: "thread-01",
      runId: "run-01",
      actionKind: "COMMUNICATE",
      capabilityRef: "capability-01",
      capabilityVersion: "1.0.0",
      operation: "publish",
      targetRefs: ["target-01"],
      resourceRefs: ["resource:article-01"],
      dataClassification: "private",
      disclosure: "named_recipients",
      recipientRefs: ["recipient:reviewer-01"],
      sideEffect: "irreversible",
      estimatedCostMicros: 1_000,
      frequency: { count: 1, intervalMs: null },
      credentialOrAccessChange: false,
      reversible: false,
      idempotencyKey: "publish-01",
      deterministicFactCodes: ["EXTERNAL_COMMUNICATION"],
      modelReasonCode: "MODEL_COMMUNICATION",
      requestedAt: "2026-08-26T00:00:00.000Z",
      expiresAt: "2026-08-26T01:00:00.000Z",
    },
    trueResultRef: null,
    generatedAt: "2026-08-26T00:00:01.000Z",
  }),
  fixture("snapshot", "capability.snapshot", {
    capabilityRef: "capability-01",
    revision: 7,
    lifecycle: "update_proposed",
    displayName: "Fixture capability",
    sourceType: "adapter",
    sourceLocator: "adapter:fixture:1.0.0",
    sourceIdentity: "publisher:fixture",
    version: "1.0.0",
    integrity: "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    signatureStatus: "verified",
    signerRef: "signer-fixture",
    operations: ["publish"],
    permissionRefs: ["permission-publish"],
    dataClassifications: ["private"],
    networkScopes: ["api.example.test:443"],
    filesystemScopes: [],
    secretRefs: ["provider-token"],
    isolation: "remote",
    currency: "USD",
    maxMicrosPerInvocation: 1_000,
    healthStatus: "healthy",
    healthCheckedAt: "2026-08-26T00:00:00.000Z",
    reviewedBy: "owner-01",
    reviewedAt: "2026-08-26T00:00:00.000Z",
    approvalRefs: ["approval-install-01"],
    dependencyTaskRefs: ["task-01"],
    runtimeQualification: {
      platform: "linux",
      runtimeIdentity: "node-fetch:adapter-fixture",
      productionSuitable: true,
      reasonCodes: [],
      checkedAt: "2026-08-26T00:00:00.000Z",
    },
    pendingVersion: "2.0.0",
    updateAssessment: {
      fromVersion: "1.0.0",
      toVersion: "2.0.0",
      disposition: "approval_required",
      risk: "critical",
      sourceIdentityChanged: false,
      integrityChanged: true,
      semanticMajorChanged: true,
      runtimeKindChanged: false,
      executableIdentityChanged: false,
      executableCodeChanged: false,
      expansions: ["permission:publish-public"],
      contractions: [],
      compatibilityPreserved: true,
      reasonCodes: ["CAPABILITY_UPDATE_MAJOR_CHANGED"],
    },
    rollbackVersion: "0.9.0",
    rollbackAvailable: true,
    lastTransition: {
      fromVersion: "0.9.0",
      toVersion: "1.0.0",
      outcome: "activated",
      occurredAt: "2026-08-26T00:00:00.000Z",
      externalEffectsRolledBack: false,
      productStateRolledBack: false,
    },
    generatedAt: "2026-08-26T00:00:01.000Z",
  }),
  fixture("snapshot", "grant.snapshot", {
    grantId: "grant-01",
    revision: 2,
    kind: "one_time",
    status: "active",
    capabilityRef: "capability-01",
    capabilityVersion: "1.0.0",
    operations: ["publish"],
    exactResourceRef: "resource:article-01",
    resourceIdentities: ["resource:article-01"],
    resourcePrefixes: [],
    maxDataClassification: "private",
    disclosure: "named_recipients",
    sideEffects: ["irreversible"],
    recipientRefs: ["recipient:reviewer-01"],
    maxCostMicrosPerUse: 1_000,
    maxFrequency: { count: 1, intervalMs: null },
    validFrom: "2026-08-26T00:00:00.000Z",
    expiresAt: "2026-08-26T01:00:00.000Z",
    uses: 0,
    maxUses: 1,
    spentCostMicros: 0,
    maxTotalCostMicros: 1_000,
    sourceApprovalRequestId: "approval-01",
    revokedAt: null,
    revocationReasonCode: null,
    affectedTaskRefs: ["task-01"],
    generatedAt: "2026-08-26T00:00:01.000Z",
  }),
] as const;

const operationsMessages = [
  fixture("command", "settings.update", {
    expectedRevision: 3,
    section: "attention",
    settingRef: "attention-default",
    valueRef: "payload-attention-setting-01",
  }),
  fixture("query", "task.detail", { jobId: "job-01" }),
  fixture("query", "inbox.detail", { inboxItemId: "inbox-01" }),
  fixture("query", "inbox.digest", { digestId: null }),
  fixture("query", "memory.detail", { memoryId: "memory-01" }),
  fixture("query", "trace.detail", { traceEventId: "trace-01" }),
  fixture("query", "settings.read", { includeIntegrations: true }),
  fixture("query", "identity.session_detail", { sessionId: "session-01" }),
  fixture("snapshot", "task.snapshot", {
    jobId: "job-01",
    revision: 2,
    status: "active",
    triggerType: "interval",
    timezone: "Asia/Tokyo",
    nextRunAt: "2026-08-26T02:00:00.000Z",
    occurrenceRef: "occurrence-01",
    occurrenceStatus: "budget_blocked",
    runRef: "run-01",
    resultRef: null,
    blockedReasonCode: "BUDGET_EXHAUSTED",
    maxCostMicros: 10_000,
    spentCostMicros: 9_000,
    requestedAttention: "NOTIFY",
    safetyFloor: "INBOX",
    effectiveAttention: "NOTIFY",
    deliveryRefs: ["delivery-01"],
    generatedAt: "2026-08-26T00:00:01.000Z",
  }),
  fixture("snapshot", "inbox.snapshot", {
    inboxItemId: "inbox-01",
    revision: 1,
    unread: true,
    priority: 80,
    attentionLevel: "INBOX",
    resultRef: "result-01",
    sourceRefs: ["task:job-01", "run:run-01"],
    duplicateKey: "fixture-inbox-result",
    createdAt: "2026-08-26T00:00:00.000Z",
    generatedAt: "2026-08-26T00:00:01.000Z",
  }),
  fixture("snapshot", "digest.snapshot", {
    digestId: "digest-01",
    windowStart: "2026-08-25T15:00:00.000Z",
    windowEnd: "2026-08-26T15:00:00.000Z",
    itemRefs: ["inbox-01"],
    sourceResultRefs: ["result-01"],
    generatedAt: "2026-08-26T15:00:01.000Z",
  }),
  fixture("snapshot", "memory.snapshot", {
    memoryId: "memory-01",
    revision: 2,
    status: "active",
    contentRef: "payload-memory-01",
    dataClassification: "sensitive",
    sourceThreadId: "thread-01",
    sourceRefs: ["message-01"],
    inference: true,
    confidencePermille: 850,
    policyVersion: "memory-policy-v1",
    sensitiveApprovalRef: "approval-memory-01",
    providerProjectionStatus: "completed",
    lastUsedAt: null,
    updatedAt: "2026-08-26T00:00:00.000Z",
    generatedAt: "2026-08-26T00:00:01.000Z",
  }),
  fixture("snapshot", "trace.snapshot", {
    traceEventId: "trace-01",
    sequence: 4,
    eventType: "model.completed",
    actorRef: "agent-01",
    parentEventRef: "trace-00",
    causationRef: "event-01",
    threadRef: "thread-01",
    runRef: "run-01",
    modelRef: "model-primary-v1",
    providerRef: "provider-primary",
    authorizationRef: "grant-01",
    capabilityRef: null,
    costMicros: 24,
    retryAttempt: 0,
    resultRef: "result-01",
    payloadRef: "payload-trace-01",
    occurredAt: "2026-08-26T00:00:00.000Z",
    generatedAt: "2026-08-26T00:00:01.000Z",
  }),
  fixture("snapshot", "settings.snapshot", {
    revision: 3,
    primaryModelRef: "model-primary-v1",
    fallbackModelRef: "model-fallback-v1",
    globalBudgetMicros: 1_000_000,
    spentBudgetMicros: 24,
    defaultAttention: "INBOX",
    digestTimezone: "Asia/Tokyo",
    digestScheduleRef: "schedule-digest-01",
    integrations: [
      {
        integrationRef: "github-app",
        status: "blocked_credentials",
        secretRefs: ["secret-github-app"],
        reasonCode: "CREDENTIALS_REQUIRED",
      },
    ],
    generatedAt: "2026-08-26T00:00:01.000Z",
  }),
  fixture("snapshot", "session.snapshot", {
    sessionId: "session-01",
    sessionRevision: 2,
    status: "active",
    deviceId: "device-01",
    deviceLabel: "Owner MacBook",
    deviceStatus: "active",
    authenticationRef: "authentication-session-01",
    firstAuthenticatedAt: "2026-08-26T00:00:00.000Z",
    lastActiveAt: "2026-08-26T00:30:00.000Z",
    recentAuthenticatedAt: "2026-08-26T00:29:00.000Z",
    revokedAt: null,
    generatedAt: "2026-08-26T00:30:01.000Z",
  }),
  fixture("command", "host.file.prepare", {
    grantId: "directory-grant-01",
    expectedGrantRevision: 1,
    operation: "update",
    relativePathRef: "path-ref-01",
    destinationPathRef: null,
    candidatePayloadRef: "payload-candidate-01",
    redactedDiffRef: "payload-diff-01",
    irreversibleScopeRef: null,
    expiresAt: "2026-08-26T01:00:00.000Z",
  }),
  fixture("command", "host.file.execute", {
    operationPlanRef: "file-operation-01",
    expectedRevision: 1,
    operation: "permanent_delete",
    canonicalHash: "sha256-file-operation-01",
    recentAuthenticationRef: "authentication-recent-01",
  }),
  fixture("command", "workspace.stage", {
    workspaceSnapshotId: "workspace-snapshot-01",
    expectedTaskChangeSetRevision: 2,
    taskPathRefs: ["path-ref-task-01"],
    validationResultRefs: ["validation-01"],
    commitMessageRef: "payload-commit-message-01",
    expiresAt: "2026-08-26T01:00:00.000Z",
  }),
  fixture("command", "workspace.commit", {
    commitPreviewId: "commit-preview-01",
    expectedRevision: 1,
    semanticSnapshotHash: "sha256-commit-preview-01",
    recentAuthenticationRef: "authentication-recent-01",
  }),
  fixture("query", "host.directory.detail", { grantId: "directory-grant-01" }),
  fixture("query", "workspace.detail", { workspaceId: "workspace-01" }),
  fixture("query", "workspace.list", { afterCursor: null, limit: 50 }),
  fixture("snapshot", "host.directory.snapshot", {
    grantId: "directory-grant-01",
    revision: 1,
    hostId: "host-mac",
    displayPath: "/fixture/workspace",
    operations: ["read", "create", "update", "move", "trash", "restore"],
    pathPolicy: "same_filesystem_no_links",
    mountPolicy: "fixed_device",
    disclosure: "model",
    expiresAt: "2026-08-26T01:00:00.000Z",
    revokedAt: null,
    preparedOperationRefs: ["file-operation-01"],
    trashRecordRefs: [],
    recoveryRefs: ["recovery-01"],
    generatedAt: "2026-08-26T00:00:01.000Z",
  }),
  fixture("snapshot", "workspace.snapshot", {
    workspaceId: "workspace-01",
    snapshotId: "workspace-snapshot-01",
    revision: 1,
    hostId: "host-mac",
    repositoryKind: "git",
    branch: "main",
    head: "commit-head-01",
    upstreamObservation: "origin/main",
    detached: false,
    unborn: false,
    taskChangeSetRevision: 2,
    ownerPathRefs: ["path-ref-owner-01"],
    taskPathRefs: ["path-ref-task-01"],
    concurrentPathRefs: [],
    commandProfileRefs: ["command-profile-01"],
    commandObservationRefs: ["command-observation-01"],
    commitPreviewRef: "commit-preview-01",
    recoveryRefs: ["recovery-01"],
    directoryGrantRefs: ["directory-grant-01"],
    generatedAt: "2026-08-26T00:00:01.000Z",
  }),
] as const;

export const autonomyMessages = [
  fixture("command", "suggestion.respond", {
    suggestionId: "suggestion-01",
    expectedRevision: 2,
    decision: "approve",
  }),
  fixture("command", "reflection.configure", {
    expectedRevision: 1,
    schedule: "daily:09:00",
    timezone: "Asia/Tokyo",
    dailySuggestionQuota: 3,
    maximumContextItems: 50,
    maximumCostMicros: 1000,
    timeoutMs: 30000,
    maximumCandidates: 3,
    enabled: true,
  }),
  fixture("command", "improvement.review", {
    candidateId: "improvement-01",
    expectedRevision: 4,
    decision: "request_revision",
    reviewEvidenceRef: "payload-review-01",
  }),
  fixture("query", "suggestion.list", { status: null, afterCursor: null, limit: 50 }),
  fixture("query", "suggestion.detail", { suggestionId: "suggestion-01" }),
  fixture("query", "reflection.detail", { includeCheckpoints: true }),
  fixture("query", "delegation.detail", { delegationId: "delegation-01" }),
  fixture("query", "delegation.list", { status: null, afterCursor: null, limit: 50 }),
  fixture("query", "improvement.list", { status: "review_required", afterCursor: null, limit: 50 }),
  fixture("query", "improvement.detail", { candidateId: "improvement-01" }),
  fixture("snapshot", "suggestion.snapshot", {
    suggestionId: "suggestion-01",
    revision: 2,
    status: "delivered",
    kind: "goal-follow-up",
    titleRef: "payload-title-01",
    bodyRef: "payload-body-01",
    evidenceRefs: ["evidence-01"],
    sourceWatermark: "watermark-01",
    goalRef: "goal-01",
    commitmentRef: null,
    confidencePermille: 800,
    noveltyPermille: 700,
    semanticKey: "sha256-semantic-01",
    estimatedCapabilityRefs: ["capability-read-01"],
    estimatedDataClassifications: ["private"],
    estimatedCostMicros: 100,
    deliveryRef: "inbox-01",
    taskRef: null,
    createdAt: "2026-08-26T00:00:00.000Z",
    expiresAt: "2026-08-27T00:00:00.000Z",
    generatedAt: "2026-08-26T00:00:01.000Z",
  }),
  fixture("snapshot", "reflection.snapshot", {
    revision: 1,
    schedule: "daily:09:00",
    timezone: "Asia/Tokyo",
    dailySuggestionQuota: 3,
    maximumContextItems: 50,
    maximumCostMicros: 1000,
    timeoutMs: 30000,
    maximumCandidates: 3,
    enabled: true,
    latestInputWatermark: "watermark-01",
    latestOutcome: "no_change",
    latestErrorCode: null,
    generatedAt: "2026-08-26T00:00:01.000Z",
  }),
  fixture("snapshot", "delegation.snapshot", {
    delegationId: "delegation-01",
    revision: 2,
    parentRunId: "run-01",
    workerRunId: "worker-run-01",
    traceRef: "trace-01",
    subtaskRef: "payload-subtask-01",
    outputSchemaRef: "payload-output-schema-01",
    contextRefs: ["payload-context-01"],
    capabilityHandleRefs: ["handle-read-01"],
    allowedModelRefs: ["model-worker-01"],
    dataClassification: "private",
    maximumDurationMs: 30000,
    maximumCostMicros: 1000,
    maximumProgressEvents: 10,
    status: "running",
    resultRef: null,
    failureReasonCode: null,
    createdAt: "2026-08-26T00:00:00.000Z",
    updatedAt: "2026-08-26T00:00:01.000Z",
    generatedAt: "2026-08-26T00:00:01.000Z",
  }),
  fixture("snapshot", "improvement.snapshot", {
    candidateId: "improvement-01",
    revision: 4,
    baseRevision: "commit-base-01",
    baseDigest: "sha256-base-01",
    observableProblemRef: "payload-problem-01",
    goalRef: "payload-goal-01",
    invariantRefs: ["invariant-no-regression-01"],
    allowedPathRefs: ["path-packages-feature-01"],
    patchRef: "payload-patch-01",
    patchDigest: "sha256-patch-01",
    validationRefs: ["validation-01"],
    comparisonRef: "comparison-01",
    artifactRef: "payload-artifact-01",
    artifactDigest: "sha256-artifact-01",
    risk: "medium",
    protectedRootFacts: [],
    status: "review_required",
    reviewRequired: true,
    expiresAt: "2026-08-27T00:00:00.000Z",
    generatedAt: "2026-08-26T00:00:01.000Z",
  }),
] as const;

export const compatibilityMessages = [
  ...messages.map((message) =>
    message.type === "approval.respond"
      ? {
          ...message,
          payload: {
            ...message.payload,
            expectedRevision: 1,
            recentAuthenticationRef: "recent-auth-01",
          },
        }
      : message,
  ),
  ...governanceMessages,
  ...operationsMessages,
  ...autonomyMessages,
];
